services:
  - type: web
    plan: free
    name: File-Sharing-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Abhyudak/File-Sharing-Bot.git      
    branch: main
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB_MESSAGE 
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: DATABASE_NAME 
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: CUSTOM_CAPTION
        sync: false
      - key: START_MESSAGE 
        sync: false
      - key: ADMINS 
        sync: false
      - key: TG_BOT_TOKEN
        sync: false 
      - key: OWNER_ID 
        sync: false  
      - key: CHANNEL_ID
        sync: false
      - key: DISABLE_CHANNEL_BUTTON
        sync: false
    autoDeploy: false 
